kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: redeploy-operator
  namespace: redeploy-operator
rules:
- apiGroups:
  - app.thatinfrastructureguy.com
  resources:
  - redeploies
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
- apiGroups:
  - "*"
  resources:
  - services
  verbs:
  - create

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: redeploy-operator
subjects:
- kind: ServiceAccount
  name: redeploy-operator
  namespace: redeploy-operator
roleRef:
  kind: ClusterRole
  name: redeploy-operator
  apiGroup: rbac.authorization.k8s.io
